Test for `grep` exit codes >1.

diff --git a/bin/dot-only-hunter b/bin/dot-only-hunter
--- a/bin/dot-only-hunter
+++ b/bin/dot-only-hunter
@@ -47,12 +47,18 @@ main () {
 
   echo "Hunting inside '$test_dir' for tests with \`.only\`..."
 
-  if grep -nR "\($prey\)\.only" "$test_dir"; then
+  grep -nR "\($prey\)\.only" "$test_dir"
+  rc=$?
+  if [[ $rc -eq 0 ]]; then
     echo "Whoops! Found \`.only\` in your tests."
     exit 1
+  elif [[ $rc -gt 1 ]] ; then
+    echo "Error searching for\`.only\` in your tests. This system may be incompatible."
+    exit 1
+  else
+    echo "All good!"
   fi
 
-  echo "All good!"
 }
 
 parse_cmd_args "$@"
